#!/bin/sh

#----------1. defining an array ----------#
array[0]=0
array[5]=5
echo "the array is [0,\\,\\,\\,\\,5,\\...]"

echo "array[0]: ${array[0]}"
echo array[1]: ${array[1]}
echo array[5]: ${array[5]}
echo array[6]: ${array[6]}		# none
echo $array				# first elements

unset array
#----------2. defining an array ----------#
echo "===================================="
arr=(apple orange peach bear banana watermelon)
echo "(${arr[*]})"

echo "the first element:"
echo $arr
echo ${arr[0]}

echo "length of the first element:"
echo ${#arr}
echo ${#arr[0]}

echo "length of the array:"
echo ${#arr[@]}
echo ${#arr[*]}

echo "all elements:"
echo ${arr[@]}
echo ${arr[*]}
echo ${arr[@]:0}
echo ${arr[*]:0}

echo "slice elements:"
echo ${arr[@]:1}
echo ${arr[*]:2}
echo ${arr[@]:2:3}
echo ${arr[*]:2:1}

#---------- 3. ----------#
echo "==============================="
unset arr
arr=$(1..32)
echo ${#arr[@]}
